name: Go build and push img on GCR

env:
   DOCKER_REG: "ghcr.io/codesensegroup/freenombot"
   REG: "ghcr.io"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
    - name: Login Docker
      run:
        echo ${{ secrets.FrankCR_PAT }} | docker login $REG -u frank30941 --password-stdin
    - name: Build Image
      run:
        cd docker/build/
        docker build ./docker/build/Dockerfile --file Dockerfile --tag image
    - name: Push Image
      run:
        |
        # Strip git ref prefix from version
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        # Strip "v" prefix from tag name
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        # Use Docker `latest` tag convention
        [ "$VERSION" == "master" ] && VERSION=latest
        echo IMAGE_ID=$DOCKER_REG
        echo VERSION=$VERSION
        docker tag image $DOCKER_REG:$VERSION
        docker push $DOCKER_REG:$VERSION
